---
galaxy_info:
  role_name: medical_compose
  author: PPS
  description: Sincroniza el repo y ejecuta docker compose para Aplicación Médica
  license: MIT
  min_ansible_version: "2.14"
dependencies: []
